#!/bin/bash

SOURCE_DIR=`pwd`
BUILD_DIR=build
BUILD_TYPE=debug
INSTALL_DIR=${BUILD_TYPE}-install
BUILD_NO_EXAMPLES=0

mkdir -p ${BUILD_DIR}/${BUILD_TYPE} \
	&& cd ${BUILD_DIR}/${BUILD_TYPE} \
	&& cmake \
		-DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
		-DCMAKE_BUILD_NO_EXAMPLES=${BUILD_NO_EXAMPLES} \
		${SOURCE_DIR} \
	&& make $*
