#!/bin/bash

SOURCE_DIR=`pwd`
BUILD_DIR=build
BUILD_TYPE=release
INSTALL_DIR=${BUILD_TYPE}-install
BUILD_PLAT_MINGW=0
# lua pkg-config
#BUILD_LUA_PC=luajit
BUILD_NO_SHARED=0
BUILD_NO_EXAMPLES=0

mkdir -p ${BUILD_DIR}/${BUILD_TYPE} \
	&& cd ${BUILD_DIR}/${BUILD_TYPE} \
	&& cmake \
		-DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
		-DCMAKE_BUILD_PLAT_MINGW=${BUILD_PLAT_MINGW} \
		-DCMAKE_BUILD_LUA_PC=${BUILD_LUA_PC} \
		-DCMAKE_BUILD_NO_SHARED=${BUILD_NO_SHARED} \
		-DCMAKE_BUILD_NO_EXAMPLES=${BUILD_NO_EXAMPLES} \
		# -DCMAKE_INSTALL_PREFIX=/usr/local \
		${SOURCE_DIR} \
	&& make $*
